# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/dubai/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),dubai)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,8d2627e02aeddf643a21f01253b5102a0e5fb2bc)
$(call add-radio-file-sha1-checked,radio/modem.img,2b984de8464d1d307162d85b4833cf98d2abf04e)
$(call add-radio-file-sha1-checked,radio/abl.img,8680259a8d124778029ac525877390a11312b674)
$(call add-radio-file-sha1-checked,radio/aop.img,b944816d2b8b3d7dfd380e56c6d69f7974e6c187)
$(call add-radio-file-sha1-checked,radio/cpucp.img,e19ca4486ab9b7c6347bd6389419168d23d205ea)
$(call add-radio-file-sha1-checked,radio/devcfg.img,511f904194d303d8b574710ec61fb72071388b37)
$(call add-radio-file-sha1-checked,radio/dsp.img,72c78cc1886db44fdb7893f8734a002552151a50)
$(call add-radio-file-sha1-checked,radio/fsg.img,3f9b9b30e61f33ac73db247cd6d272f0296c7139)
$(call add-radio-file-sha1-checked,radio/hyp.img,98f3e3d879743679fbc2596d9c6c258e3970f47b)
$(call add-radio-file-sha1-checked,radio/keymaster.img,6540a9c5ad93456ccd776ca7dae05336f0a881c0)
$(call add-radio-file-sha1-checked,radio/logo.img,13557ffda78931d548b0d9b47f0b8e0bdaea85a5)
$(call add-radio-file-sha1-checked,radio/prov.img,bf9f2a5f5f974d727b532a422428247cc0ccf8ff)
$(call add-radio-file-sha1-checked,radio/qupfw.img,09980f77eedc41719537465e80fe78faae44d688)
$(call add-radio-file-sha1-checked,radio/shrm.img,2b2b0ded6e8bc45d8b3cce64a83ffc5b179f78b8)
$(call add-radio-file-sha1-checked,radio/storsec.img,7a9d38457c5fbeae60c0a03d0cee3522557f789f)
$(call add-radio-file-sha1-checked,radio/tz.img,74a077db49688a43402f9afaa5783abb36a2e7f8)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,03d1e03b8de2688777632332abfef1973473cdf6)
$(call add-radio-file-sha1-checked,radio/xbl.img,70f0bb3fb59facf5afd5cb58c50b2b95317e9e45)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,36271da5285e55985c3ce7158663ddf08875549f)

endif
