# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/dubai/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),dubai)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,b745d7dd971a95a4e91fea5b948192effefe2916)
$(call add-radio-file-sha1-checked,radio/modem.img,6f35b92a2330541d9728afaf28e2acbf9aae396c)
$(call add-radio-file-sha1-checked,radio/abl.img,9a080d6f4ed4ae43b15c623f02c166b1a30044e2)
$(call add-radio-file-sha1-checked,radio/aop.img,36ec3d284932ce1bc168476b2f808c9eea16cbc0)
$(call add-radio-file-sha1-checked,radio/cpucp.img,0d2fc0065b168e0fe2cb30bbf5c639462bb32e71)
$(call add-radio-file-sha1-checked,radio/devcfg.img,bf02513e9fa0467c2f4b45a33e23009dd23cfbca)
$(call add-radio-file-sha1-checked,radio/dsp.img,72c78cc1886db44fdb7893f8734a002552151a50)
$(call add-radio-file-sha1-checked,radio/fsg.img,3f9b9b30e61f33ac73db247cd6d272f0296c7139)
$(call add-radio-file-sha1-checked,radio/hyp.img,e88b089c253ee62c09f919dec11847073341a390)
$(call add-radio-file-sha1-checked,radio/keymaster.img,2d6a75921b2d896ff37857a75fe438784370f74a)
$(call add-radio-file-sha1-checked,radio/logo.img,aca3792172c12a3f190baa42178abcd9b0b7d67e)
$(call add-radio-file-sha1-checked,radio/prov.img,29a4e483f08eedb6f012e3423f3725146763fa7c)
$(call add-radio-file-sha1-checked,radio/qupfw.img,0c695d378d2f33e1964de2468f1a663039666b1c)
$(call add-radio-file-sha1-checked,radio/shrm.img,76eab9cca12baead612afd70d33c03967bfff915)
$(call add-radio-file-sha1-checked,radio/storsec.img,9ad21c25c4e098e9a0398b6b9176173055b2fb43)
$(call add-radio-file-sha1-checked,radio/tz.img,bfcbfff924fd4ae47fad4357341ff8e85841ebae)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,a5d9d9c1765b395de36175724f80682401da2224)
$(call add-radio-file-sha1-checked,radio/xbl.img,7e100ed7334278a5ccf0a6e91dd66dae16607042)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,7e42594b767f417dcd40eafa442a1960ced914f4)

endif
