# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/dubai/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),dubai)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,9709c4630d9441ff4b747a739612f64b185b4718)
$(call add-radio-file-sha1-checked,radio/modem.img,2c792106d61fce2099242bc5b6f886bf61d1c18a)
$(call add-radio-file-sha1-checked,radio/abl.img,3c66ecae15741cbc97bf0c0366b8d746ba672c47)
$(call add-radio-file-sha1-checked,radio/aop.img,aa197952a67827a117bab2f3ed8aba004503ca33)
$(call add-radio-file-sha1-checked,radio/cpucp.img,6ad0dd3d24f47355fd253e65294b00d4afdd716e)
$(call add-radio-file-sha1-checked,radio/devcfg.img,649593ae593e2d66e6575204e1dd10fe67eeaa2c)
$(call add-radio-file-sha1-checked,radio/dsp.img,72c78cc1886db44fdb7893f8734a002552151a50)
$(call add-radio-file-sha1-checked,radio/fsg.img,fdc049cfbeec541547fde2399bb228f56f0a74d5)
$(call add-radio-file-sha1-checked,radio/hyp.img,3895321be268c708e6c071287def9456d7774ddc)
$(call add-radio-file-sha1-checked,radio/keymaster.img,b9b4ae9f68b988bafe18c36ec9a3645a6cf8b6e8)
$(call add-radio-file-sha1-checked,radio/logo.img,69e998ca67ce51f9639662675156001bfc5d2c08)
$(call add-radio-file-sha1-checked,radio/prov.img,7326738ddfebb079f698298e3026bd6c6523c916)
$(call add-radio-file-sha1-checked,radio/qupfw.img,f51f1ea2cb9678661825b19104a57365cccffaf5)
$(call add-radio-file-sha1-checked,radio/shrm.img,a04339f195ee8ca1d104eff52cd839e756c2010b)
$(call add-radio-file-sha1-checked,radio/storsec.img,4156ba45da361ae27808e47681ab6f77b4e68275)
$(call add-radio-file-sha1-checked,radio/tz.img,bdee029d6ebc1a67f3c2f50758657e7648194e48)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,6209fc853346838e85e3094a7862a7a76e306399)
$(call add-radio-file-sha1-checked,radio/xbl.img,5a277fe25460d8ff6f84f098e2d215dfa11795a1)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,223af7aac0674ef132324ed16544d6d3d7736dc6)

endif
